# CFS-Chameleon統合設定ファイル
# Collaborative Feature Sharing + Chameleon Configuration

# 基本モデル設定（既存Chameleonと互換）
model:
  name: "meta-llama/Llama-3.2-3B-Instruct"
  device: "cuda"  # auto, cuda, cpu
  torch_dtype: "float32"  # float32, float16, bfloat16
  max_length: 128  # 改善: 50→128 (入力長を考慮した適切な値)
  max_new_tokens: 30  # 新規: 生成トークン数の明示的制限
  batch_size: 4

# Chameleon基本設定（既存互換）
chameleon:
  alpha_personal: 0.3
  alpha_general: -0.05
  num_self_generated: 10
  target_layers:
    - "model.layers.14.mlp"
  theta_p_path: "chameleon_prime_personalization/processed/LaMP-2/theta_p.npy"
  theta_n_path: "chameleon_prime_personalization/processed/LaMP-2/theta_n.npy"
  direction_p_path: "chameleon_prime_personalization/processed/LaMP-2/theta_p.npy"
  direction_n_path: "chameleon_prime_personalization/processed/LaMP-2/theta_n.npy"

# CFS協調機能設定（新機能）
collaboration:
  # 協調機能有効化フラグ
  enable_collaboration: true
  
  # 協調方向プール設定
  direction_pool:
    pool_size: 1000              # プール最大容量
    rank_reduction: 32           # SVD分解ランク
    cleanup_threshold: 0.8       # プール満杯時のクリーンアップしきい値
    
  # ピース選択設定
  piece_selection:
    top_k_pieces: 10             # 選択するピース数
    selection_strategy: "analytical"  # analytical, learned
    context_weight: 0.3          # コンテキスト類似度重み
    semantic_weight: 0.3         # 意味的関連性重み
    quality_weight: 0.2          # 品質スコア重み
    user_similarity_weight: 0.2  # ユーザー類似度重み
    
  # 方向統合設定
  direction_fusion:
    fusion_strategy: "analytical"    # analytical, weighted_attention, meta_learning
    normalization: true              # 統合後の正規化
    importance_weighting: true       # 重要度による重み付け
    
  # プライバシー保護設定
  privacy:
    enable_noise: true           # 差分プライバシーノイズ有効化
    noise_std: 0.01             # ノイズ標準偏差
    noise_type: "gaussian"      # gaussian, laplacian
    clip_threshold: 1.0         # 方向ベクトルクリッピング閾値
    
  # 軽量学習設定（オプション）
  learning:
    enable_learning: false      # 学習コンポーネント有効化
    gate_network:
      embedding_dim: 768
      num_directions: 200
      hidden_dim: 256
      dropout_rate: 0.1
    training:
      learning_rate: 1e-3
      batch_size: 16
      epochs: 10
      validation_split: 0.2
      
  # キャッシング設定
  caching:
    enable_similarity_cache: true    # 類似度キャッシュ有効化
    cache_size: 10000               # キャッシュサイズ
    cache_ttl: 3600                 # キャッシュ有効時間（秒）

# 評価設定（既存と互換）
evaluation:
  max_users: 20
  metrics:
    - "exact_match"
    - "bleu_score"
    - "f1_score"
    - "collaboration_benefit"  # 新メトリク
  save_predictions: true
  enable_statistical_test: true
  confidence_level: 0.05

# データソース設定（既存と互換）
data_sources:
  primary: "chameleon_prime_personalization/data/raw/LaMP-2/merged.json"
  answers_primary: "chameleon_prime_personalization/data/raw/LaMP-2/answers.json"
  backup: "data/raw/LaMP_all/LaMP_2/user-based/dev/dev_questions.json"
  answers_backup: "data/raw/LaMP_all/LaMP_2/user-based/dev/dev_outputs.json"
  theta_vectors:
    personal: "processed/LaMP-2/theta_p.json"
    neutral: "processed/LaMP-2/theta_n.json"

# CFS状態管理設定
state_management:
  auto_save: true                      # 自動状態保存
  save_interval: 300                   # 保存間隔（秒）
  save_directory: "./cfs_state"       # 状態保存ディレクトリ
  max_saved_states: 10                # 最大保存状態数
  compression: true                    # 状態データ圧縮

# 実験モード設定
experiment:
  mode: "production"  # development, testing, production
  debug_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  enable_profiling: false
  profile_output: "./cfs_profiles"
  
  # A/Bテスト設定
  ab_testing:
    enable: false
    split_ratio: 0.5
    control_group: "legacy_chameleon"
    treatment_group: "cfs_chameleon"
    
# パフォーマンス最適化設定
performance:
  # 並列処理設定
  parallel_processing:
    enable: true
    max_workers: 4
    chunk_size: 32
    
  # メモリ管理
  memory_management:
    enable_garbage_collection: true
    gc_interval: 100
    max_memory_usage_mb: 8192
    
  # 計算最適化
  computation:
    use_mixed_precision: false      # 混合精度計算
    enable_torch_compile: false     # PyTorch 2.0 compile
    cache_embeddings: true          # 埋め込みキャッシュ

# モニタリング・ロギング設定
monitoring:
  enable_metrics: true
  metrics_output: "./cfs_metrics"
  
  # ロギング設定
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file_output: "./logs/cfs_chameleon.log"
    max_file_size_mb: 100
    backup_count: 5
    
  # パフォーマンス監視
  performance_monitoring:
    enable: true
    sample_rate: 0.1
    track_memory: true
    track_gpu_usage: true
    alert_thresholds:
      memory_usage_percent: 80
      processing_time_ms: 1000

# 互換性設定
compatibility:
  maintain_legacy_api: true           # 既存API互換性維持
  enable_fallback: false             # 改善: フォールバック無効化（デバッグ用）
  strict_mode: true                  # 新規: エラー時の厳密動作
  legacy_mode_available: true        # レガシーモード利用可能
  migration_support: true            # マイグレーション支援

# セキュリティ設定
security:
  enable_input_validation: true      # 入力検証
  sanitize_user_data: true          # ユーザーデータサニタイズ
  secure_state_storage: true        # 状態データ暗号化
  audit_logging: true               # 監査ログ
  
# 出力設定
output:
  results_directory: "./results"
  collaboration_results_directory: "./cfs_results"
  enable_visualization: true
  plot_formats: ["png", "pdf"]
  export_formats: ["json", "csv", "parquet"]

# デバッグ・開発設定
development:
  enable_debug_mode: true            # 改善: デバッグモード有効化
  verbose_logging: true              # 改善: 詳細ログ有効化
  save_intermediate_results: true    # 改善: 中間結果保存有効化
  enable_assertions: true
  test_mode: false
  debug_hooks: true                  # 新規: フック動作のデバッグ
  log_generation_steps: true         # 新規: 生成ステップのログ
  
  # 開発用データ設定
  use_synthetic_data: false
  synthetic_data_size: 1000
  random_seed: 42

# バージョン情報
version:
  cfs_chameleon_version: "1.0.0"
  config_version: "1.0.0"
  compatibility_version: "chameleon_1.x"
  last_updated: "2025-01-04"